### ISSUE TITLE
Missing composer autoload parameter

### ISSUE THREAD

**Issue by danieltrolezi** [hownowstephen/php-foursquare#28]
Hi! First of all, i want to thank you. This sdk really made my life easier and it is a great job! 
I've been using your sdk in my application for the last year, not by Composer though. Now, I decided to use Composer with all my dependecies.

The problem is, the autoload isn't loading your class, I think you missed the autoload parameter in you composer.json. Since the FoursquareAPI.class.php file is inside the "src" directory, I think it should be something like that:

<pre>{
    "autoload": {
        "psr-0": { "FoursquareAPI.class": "src/" }
    }
}</pre>

Maybe I'm doing something wrong, but every other libraries that I installed through Composer are ok.
Anyway, can you help me? Thank you so much!

**Comment by iworker** [comment]
+1

**Comment by danieltrolezi** [comment]
For those who have the same problem, here's a temporary solution:
Add these lines in YOUR composer.json file:

<pre>
"autoload": {
    "classmap": [
      "vendor/hownowstephen/php-foursquare/src/"
    ]
  }
</pre>

**Comment by hownowstephen** [comment]
fixed in b2d7f6bb277d17702527a896108ff25567846860 thanks @danieltrolezi for the patch
