### ISSUE TITLE
blank page

### ISSUE THREAD

**Issue by Mik-A** [hownowstephen/php-foursquare#30]
Sorry I´m new to github so I didn´t know where to place question.
I put my ClintId and Secret. qas there anything else?
I tried to try public.php but it returns a blank page.

**Comment by IacopoC** [comment]
Experiencing error in public.php after inserting my credentials, I can't see results after searching.
**Notice**: Trying to get property of non-object in php-foursquare\examples\public.php

**Comment by hownowstephen** [comment]
I've just updated `public.php` and added some extra instructions https://github.com/hownowstephen/php-foursquare/tree/master/examples - tested with a fresh set of credentials from the foursquare API and getting results. Let me know if you continue to see an error, happy to help debug further
