### ISSUE TITLE
Swarm checkin right now here not showing

### ISSUE THREAD

**Issue by cepedit** [hownowstephen/php-foursquare#33]
My problem swarm checkin  after venue right now here not showing

**Comment by hownowstephen** [comment]
Hi there, could you please provide a code sample and describe more fully the expected behaviour, so I can better understand what issue you're having / which endpoint you're trying to query? I am not too familiar with Swarm, but am [not seeing much](https://developer.foursquare.com/docs/search?query=swarm) in the way of documentation around it in the Foursquare API

**Comment by cepedit** [comment]
Hi stephen https://developer.foursquare.com/docs/api/checkins/add

**Comment by hownowstephen** [comment]
I don't really have any information about what you're looking to do here, but you should be able to send a POST to that endpoint using something like the following:

```php
<?php
// create a client
$foursquare = new FoursquareApi("<ClientID>", "<ClientSecret>");

// XXX: generate an access token...see https://github.com/hownowstephen/php-foursquare/blob/master/examples/tokenrequest.php
$foursquare->SetAccessToken($myGeneratedAccessToken);

// populate with your venue information and any other params
$params = array("venueId"=>"<VenueID>");

// make the request
$response = $foursquare->GetPrivate("checkins/add",$params,true);
// print to stdout
var_dump($response);
?>
```

I've just tested it out and performed a successful check-in at Central Park via my development app.

<img width="645" alt="screen shot 2018-10-10 at 11 42 04 am" src="https://user-images.githubusercontent.com/661424/46748462-9ce68280-cc81-11e8-896b-87ec708a1185.png">

hopefully this helps. Closing off the issue, if you are still having trouble feel free to re-open, but you're going to need to provide more clear detail / code samples for me to help you debug any further

**Comment by cepedit** [comment]
This check-in  success but Right now he not showing and private on I see other swarm user not showing

**Comment by hownowstephen** [comment]
That sounds like a privacy settings issue, but I'm not very familiar with those settings in foursquare, you may want to review their documentation around privacy settings (you'll notice there's a `private` field on the checkins API https://developer.foursquare.com/docs/api/checkins/details which indicates the checkin is only visible to the creator). 

It may help you to reach out to their API support, as it doesn't sound like this is specifically an issue related to the client library. However, a single sentence describing your issue doesn't give me any idea as to what's going wrong, really. When requesting help from open source maintainers, a good request contains:

- A detailed description of the behaviour you're expecting
- A description of what you've tried
- Links to any specific resources you're accessing (for example, the venues you're checking in or the user who is checking into them)
- Links to any documentation you've looked at so far
- A code sample showing what you're doing with my library

If you'd like me to help further, please provide a more detailed query with the above and I'll see if I have any insight I can provide.

**Comment by cepedit** [comment]
stephen how do I contact you?

**Comment by hownowstephen** [comment]
This is the right place to contact me, this is an open source library and any help I give I would like to remain public to ensure any answers I give can help anyone else in the community as well.

If you are continuing to have problems _specific to this library_ please follow up with details as requested either by re-opening this issue or filing a separate issue if you'd prefer.  From [what appears to be your same question](https://stackoverflow.com/questions/52343595/foursquare-offical-api-check-in-right-now-here-not-showing) on stackoverflow, I still don't know what the problem you're running into is? From the code sample there, a 
```json
{"meta":{"code":200,"requestId":"5b9ccec64c1f670d94339b66"}
```
indicates that the check-in succeeded. As I mentioned, it may be that the check-in you performed is private to the user who performed it, (or there is some other privacy setting that is getting in the way). I wrote this library a long time ago, and am in no way an expert in Foursquare, so I can't really help any further when it comes to specifics like that.

If you'd like further help, please follow my earlier request in supplying more detailed information about how the behaviour you're seeing is different from what you're expecting.
